# https://taskfile.dev

version: '3'

includes:
  nix-darwin:
    taskfile: ./nix-darwin/Taskfile.yml
    dir: ./nix-darwin
  nixos:
    taskfile: ./nixos/Taskfile.yml
    dir: ./nixos
  base:
    taskfile: ./base/Taskfile.yml
    dir: ./base