# https://taskfile.dev

version: "3"

tasks:
  list:
    desc: List all archetypes currently available
    vars:
      ARCHETYPES:
        sh: "ls -d1 {{.TASKFILE_DIR}}/*/"
    cmds:
      - echo -e "\033[1;34mListing all nix archetypes at {{.TASKFILE_DIR}} \033[0m"
      - for: { var: ARCHETYPES, as: ITEM }
        cmd: basename {{.ITEM}}
    silent: true
  activate:*:
    desc: Activate a nix archetypes main flake and taskfile ; prevents accidental builds ; cleans task output
    vars:
      NIXCONFIG: '{{index .MATCH 0}}'
    preconditions:
      - sh: test -d {{.TASKFILE_DIR}}/{{.NIXCONFIG}}
        msg: 'Provide a valid nix archetype name. Provided: {{.NIXCONFIG}}'
      - sh: test -f {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/flake.inactive.nix
        msg: 'The flake.nix at {{.NIXCONFIG}} is not inactive! (must be flake.inactive.nix)'
      - sh: test -f {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/Taskfile.inactive.yml
        msg: 'The Taskfile.yml at {{.NIXCONFIG}} is not inactive! (must be Taskfile.inactive.yml)'
    status:
      - test -f {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/flake.nix
      - test -f {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/Taskfile.yml
    cmds:
      - mv {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/flake.inactive.nix {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/flake.nix
      - mv {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/Taskfile.inactive.yml {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/Taskfile.yml
  deactivate:*:
    desc: Deactivates a nix archetype main flake and taskfile
    vars:
      NIXCONFIG: '{{index .MATCH 0}}'
    preconditions:
      - sh: test -d {{.TASKFILE_DIR}}/{{.NIXCONFIG}}
        msg: 'Provide a valid nix archetype name. Provided: {{.NIXCONFIG}}'
      - sh: test -f {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/flake.nix
        msg: 'The flake.nix at {{.NIXCONFIG}} is not active! (must be flake.nix not flake.inactive.nix)'
      - sh: test -f {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/Taskfile.yml
        msg: 'The Taskfile.yml at {{.NIXCONFIG}} is not active! (must be Taskfile.yml not Taskfile.inactive.yml)'
    status:
      - test -f {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/flake.inactive.nix
      - test -f {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/Taskfile.inactive.yml
    cmds:
      - mv {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/flake.nix {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/flake.inactive.nix
      - mv {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/Taskfile.yml {{.TASKFILE_DIR}}/{{.NIXCONFIG}}/Taskfile.inactive.yml