# https://taskfile.dev

version: '3'

vars:
  VERSION: "25.05"

tasks:
  default:
    desc: Switch / rebuild nix-darwin configuration
    cmds:
      - sudo -H darwin-rebuild switch --flake {{.TASKFILE_DIR}}#vgmacbook
  
  init:
    desc: First time init nix-darwin
    cmds:
      - sudo -H nix --extra-experimental-features "nix-command flakes" run nix-darwin/nix-darwin-{{.VERSION}}#darwin-rebuild -- switch --flake {{.TASKFILE_DIR}}#vgmacbook

  up:
    desc: Update all flake inputs
    cmds:
      - nix flake update