" Enable line numbers and syntax highlighting
syntax on
set number
set relativenumber

" Use 4 spaces for indentation
set tabstop=4
set shiftwidth=4
set expandtab

" Enable mouse support
set mouse=a

" Highlight current line
set cursorline

" Use system clipboard (if available)
set clipboard=unnamedplus

" Set colorscheme (fallback if available)
colorscheme default

