# https://taskfile.dev

version: '3'

vars:
  DIR: ~/dotfiles

# unfortunately must use absolute paths here (in only this root taskfile) for the global taskfile via `link` task to work
includes:
  nix-base:
    taskfile: ~/dotfiles/nix/nix-base/Taskfile.yml
    dir: ./nix/nix-base
    optional: true
  nix-darwin:
    taskfile: ~/dotfiles/nix/nix-darwin/Taskfile.yml
    dir: ./nix/nix-darwin
    optional: true
    vars:
      NIXCONFIG: vgmacbook
      NIXPKGSVERSION: 25.05
  nixos:
    taskfile: ~/dotfiles/nix/nixos/Taskfile.yml
    dir: ./nix/nixos
    optional: true
    vars:
      NIXCONFIG: vgnixos
      NIXPKGSVERSION: 25.05
  nixos-wsl:
    taskfile: ~/dotfiles/nix/nixos-wsl/Taskfile.yml
    dir: ./nix/nixos-wsl
    optional: true
    vars:
      NIXCONFIG: vgwsl2
      NIXPKGSVERSION: 25.05

tasks:
  default:
    desc: List all commands available in taskfile
    cmds:
      - echo -e "\033[1;34mListing all tasks for {{.DIR}}\033[0m"
      - task --list {{.DIR}}
    silent: true

  gc:
    aliases: [gcgen]
    desc: 'garbage collect old (7 days) nix store entries [gcgen: clean generations, --force (flag): not just old but all]'
    cmds:
      - sudo -H nix-collect-garbage {{if eq .ALIAS "gcgen"}}-d{{end}} {{if not .CLI_FORCE}}--delete-older-than 7d{{end}}

  activate:*:
    desc: Activate a nix archetypes main flake and taskfile ; prevents accidental builds ; cleans task output
    vars:
      NIXCONFIG: '{{index .MATCH 0}}'
    preconditions:
      - test -d {{.DIR}}/nix/{{.NIXCONFIG}}
      - test -f {{.DIR}}/nix/{{.NIXCONFIG}}/flake.inactive.nix
      - test -f {{.DIR}}/nix/{{.NIXCONFIG}}/Taskfile.inactive.yml
    status:
      - test -f {{.DIR}}/nix/{{.NIXCONFIG}}/flake.nix
      - test -f {{.DIR}}/nix/{{.NIXCONFIG}}/Taskfile.yml
    cmds:
      - mv {{.DIR}}/nix/{{.NIXCONFIG}}/flake.inactive.nix {{.DIR}}/nix/{{.NIXCONFIG}}/flake.nix
      - mv {{.DIR}}/nix/{{.NIXCONFIG}}/Taskfile.inactive.yml {{.DIR}}/nix/{{.NIXCONFIG}}/Taskfile.yml

  deactivate:*:
    desc: Deactivates a nix archetype main flake and taskfile
    vars:
      NIXCONFIG: '{{index .MATCH 0}}'
    preconditions:
      - test -d {{.DIR}}/nix/{{.NIXCONFIG}}
      - test -f {{.DIR}}/nix/{{.NIXCONFIG}}/flake.nix 
      - test -f {{.DIR}}/nix/{{.NIXCONFIG}}/Taskfile.yml 
    status:
      - test -f {{.DIR}}/nix/{{.NIXCONFIG}}/flake.inactive.nix
      - test -f {{.DIR}}/nix/{{.NIXCONFIG}}/Taskfile.inactive.yml
    cmds:
      - mv {{.DIR}}/nix/{{.NIXCONFIG}}/flake.nix {{.DIR}}/nix/{{.NIXCONFIG}}/flake.inactive.nix
      - mv {{.DIR}}/nix/{{.NIXCONFIG}}/Taskfile.yml {{.DIR}}/nix/{{.NIXCONFIG}}/Taskfile.inactive.yml

  link:
    desc: Link this taskfile to the home directory (enables access via `task -g` or `task --global`)
    status:
      - test -L ~/Taskfile.yml
    cmds:
      - ln -s {{.TASKFILE}} ~/Taskfile.yml
  unlink:
    desc: Unlink this taskfile from home directory
    preconditions:
      - sh: test -L ~/Taskfile.yml
        msg: 'The ~/Taskfile.yml file must be a symlink in order to remove!'
    cmds:
      - rm ~/Taskfile.yml