# https://taskfile.dev

version: '3'

# unfortunately must use absolute paths here (in only this root taskfile) for the global taskfile via `link` task to work
includes:
  nix-base:
    taskfile: ~/dotfiles/nix/nix-base/Taskfile.yml
    dir: ./nix/nix-base
    optional: true
  nix-darwin:
    taskfile: ~/dotfiles/nix/nix-darwin/Taskfile.yml
    dir: ./nix/nix-darwin
    optional: true
    vars:
      NIXCONFIG: vgmacbook
      NIXPKGSVERSION: 25.05
  nixos:
    taskfile: ~/dotfiles/nix/nixos/Taskfile.yml
    dir: ./nix/nixos
    optional: true
    vars:
      NIXCONFIG: vgnixos
      NIXPKGSVERSION: 25.05
  nixos-wsl:
    taskfile: ~/dotfiles/nix/nixos-wsl/Taskfile.yml
    dir: ./nix/nixos-wsl
    optional: true
    vars:
      NIXCONFIG: vgwsl2
      NIXPKGSVERSION: 25.05

tasks:
  default:
    desc: List all commands available in taskfile
    dir: '{{.TASKFILE_DIR}}'
    vars:
      PWD:
        sh: cd {{.USER_WORKING_DIR}} && pwd
    cmds:
      - echo -e "\033[1;34mListing all tasks for ~/dotfiles\033[0m"
      - echo -e "{{if ne .PWD .TASKFILE_DIR}}\033[1;34mNote you are running this taskfile from another directory\033[0m{{end}}"
      - task --list
    silent: true
  gc:
    aliases: [gcgen]
    desc: 'garbage collect old (7 days) nix store entries [gcgen: clean generations, --force (flag): not just old but all]'
    cmds:
      - sudo -H nix-collect-garbage {{if eq .ALIAS "gcgen"}}-d{{end}} {{if not .CLI_FORCE}}--delete-older-than 7d{{end}}
  activate:*:
    desc: Activate a nix archetypes main flake and taskfile ; prevents accidental builds ; cleans task output
    vars:
      NIXCONFIG: '{{index .MATCH 0}}'
    preconditions:
      - test -d {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}
      - (test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/flake.nix || test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/flake.inactive.nix)
      - (test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/Taskfile.yml || test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/Taskfile.inactive.yml)
    status:
      - test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/flake.nix
      - test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/Taskfile.yml
    cmds:
      - mv {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/flake.nix {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/flake.inactive.nix
      - mv {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/Taskfile.yml {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/Taskfile.inactive.yml
  deactivate:*:
    desc: Deactivates a nix archetype main flake and taskfile
    vars:
      NIXCONFIG: '{{index .MATCH 0}}'
    preconditions:
      - test -d {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}
      - (test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/flake.nix || test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/flake.inactive.nix)
      - (test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/Taskfile.yml || test -f {{.TASKFILE_DIR}}/nix/{{.NIXCONFIG}}/Taskfile.inactive.yml)
    status:
    cmds:

  link:
    desc: Link this taskfile to the home directory (enables access via `task -g` or `task --global`)
    status:
      - test -L ~/Taskfile.yml
    cmds:
      - ln -s {{.TASKFILE}} ~/Taskfile.yml
  unlink:
    desc: Unlink this taskfile from home directory
    preconditions:
      - sh: test -L ~/Taskfile.yml
        msg: 'The ~/Taskfile.yml file must be a symlink in order to remove!'
    cmds:
      - rm ~/Taskfile.yml