# https://taskfile.dev

version: '3'

vars:
  DIR: ~/dotfiles

# unfortunately must use absolute paths here (in only this root taskfile) for the global taskfile via `link` task to work
includes:
  templates:
    taskfile: ~/dotfiles/templates/Taskfile.yml
    dir: ~/dotfiles/templates
  nix-darwin:
    taskfile: ~/dotfiles/nix/nix-darwin/Taskfile.yml
    dir: ~dotfiles/nix/nix-darwin
    optional: true
    vars:
      NIXCONFIG: vgmacbook
      NIXPKGSVERSION: 25.05
  nixos:
    taskfile: ~/dotfiles/nix/nixos/Taskfile.yml
    dir: ~/dotifles/nix/nixos
    optional: true
    vars:
      NIXCONFIG: vgnixos
      NIXPKGSVERSION: 25.05
  nixos-wsl:
    taskfile: ~/dotfiles/nix/nixos-wsl/Taskfile.yml
    dir: ~/dotfiles/nix/nixos-wsl
    optional: true
    vars:
      NIXCONFIG: vgwsl2
      NIXPKGSVERSION: 25.05
  arch:
    taskfile: ~/dotfiles/nix/Taskfile.yml
    dir: ~/dotfiles/nix

tasks:
  default:
    desc: List all commands available in taskfile across all archetypes
    cmds:
      - echo -e "\033[1;34mListing all tasks for {{.DIR}}\033[0m"
      - task --list {{.DIR}}
    silent: true
  upgrade:
    desc: Updates the nixpkgs channel and upgrades nix profile packages.
    cmds:
      - sudo -H nix-channel --update
      - sudo -H nix profile upgrade --all
  gc:
    aliases: [gcgen]
    desc: 'garbage collect old (7 days) nix store entries [gcgen: clean generations, --force (flag): not just old but all]'
    cmds:
      - sudo -H nix-collect-garbage {{if eq .ALIAS "gcgen"}}-d{{end}} {{if not .CLI_FORCE}}--delete-older-than 7d{{end}}
  link:
    desc: Link this taskfile to the home directory (enables access via `task -g` or `task --global`)
    status:
      - test -L ~/Taskfile.yml
    cmds:
      - ln -s {{.DIR}}/Taskfile.yml ~/Taskfile.yml
  unlink:
    desc: Unlink this taskfile from home directory
    preconditions:
      - sh: test -L ~/Taskfile.yml
        msg: 'The ~/Taskfile.yml file must be a symlink in order to remove!'
    cmds:
      - rm ~/Taskfile.yml