# https://taskfile.dev

version: '3'

includes:
  nix-base:
    taskfile: ./nix/nix-base/Taskfile.yml
    dir: ./nix/nix-base
  nix-darwin:
    taskfile: ./nix/nix-darwin/Taskfile.yml
    dir: ./nix/nix-darwin
  nixos:
    taskfile: ./nix/nixos/Taskfile.yml
    dir: ./nix/nixos

tasks:
  default:
    desc: List all commands available in taskfile
    cmds:
      - task --list
    silent: true
  fmt:
    desc: Format nix files in the repo
    cmds:
      - nix fmt
    silent: true
  gc:
    desc: garbage collect unsused store entries
    cmds:
      - sudo -H nix-collect-garbage --delete-older-than 7d
    silent: true
  gcgen:
    desc: garbage collect old generations
    cmds:
      - sudo -H nix-collect-garbage -d --delete-older-than 7d
    silent: true