# https://taskfile.dev

version: '3'

includes:
  home:
    taskfile: ./home/Taskfile.yml # the task file to include
    dir: ./home # which directory by default to run tasks
  nix:
    taskfile: ./nix/Taskfile.yml
    dir: ./nix

tasks:
  default:
    desc: List all commands available in taskfile
    cmds:
      - task --list
    silent: true
  fmt:
    desc: Format nix files in the repo
    cmds:
      - nix fmt
    silent: true
  gc:
    desc: garbage collect unsused store entries
    cmds:
      - sudo nix-collect-garbage --delete-older-than 7d
    silent: true
  gcgen:
    desc: garbage collect old generations
    cmds:
      - sudo nix-collect-garbage -d --delete-older-than 7d
    silent: true