# https://taskfile.dev

# sudo: you need the -H flag to use the local user environment for $HOME, otherwise it will default to root home `/var/root` : small bug fix

version: '3'

dotenv: ["config.toml"]

tasks:
  default:
    desc: Switch / rebuild nixos configuration
    cmds:
      - sudo nixos-rebuild switch --flake {{.TASKFILE_DIR}}#{{.NIXCONFIG}}

  status:
    desc: Current nix config and version
    cmds:
      - echo -e "\033[1;34mCurrently on nixos-wsl '{{.NIXCONFIG}}' configuration at version {{.NIXPKGSVERSION}}\033[0m"

  up:
    desc: Update all flake inputs
    cmds:
      - nix flake update
  
  channel-setup:
    desc: Update the nix channels with the correct nixos version
    prompt: Warning! This will remove the `nixpkgs` channel and replace it with the nixos-XX version
    status:
      - sudo -H nix-channel --list | (grep nixos-{{.NIXPKGSVERSION}} && exit 0)
    cmds:
      - sudo -H nix-channel --remove nixpkgs
      - sudo -H nix-channel --add https://nixos.org/channels/nixos-{{.NIXPKGSVERSION}} nixpkgs
      - sudo -H nix-channel --update
      - task: profile-upgrade

  profile-upgrade:
    desc: Upgrade all nix profiles after changing nixpkgs channel.
    cmds:
      - sudo -H nix profile upgrade --all