lib := 'lib.nix'
lib_dir := justfile_directory() / 'lib/lib.nix'

# List all recipes
lib_default:
    @echo -e "{{BOLD + BLUE}}Listing all recipes for dotfiles{{NORMAL}}"
    @just --list --justfile {{justfile()}} --list-heading '' --unsorted

lib_reset:
    @echo -e "{{BOLD + BLUE}}Reseting lib files{{NORMAL}}"
    rm -f {{nix-darwin_directory}}/{{lib}}
    rm -f {{nixos_directory}}/{{lib}}
    rm -f {{nixos-wsl_directory}}/{{lib}}

lib_link: lib_reset
    @echo -e "{{BOLD + BLUE}}Copying lib files to nix archetypes{{NORMAL}}"
    install {{lib_dir}} {{nix-darwin_directory}}/{{lib}}
    install {{lib_dir}} {{nixos_directory}}/{{lib}}
    install {{lib_dir}} {{nixos-wsl_directory}}/{{lib}}
