lib := 'lib.nix'
lib_dir := justfile_directory() / 'lib/lib.nix'

# List all recipes
lib_default:
    @echo -e "{{BOLD + BLUE}}Listing all recipes for dotfiles{{NORMAL}}"
    @just --list --justfile {{justfile()}} --list-heading '' --unsorted

lib_link:
    @echo -e "{{BOLD + BLUE}}Listing all recipes for dotfiles{{NORMAL}}"
    ln -sf {{lib_dir}} {{nix-darwin_directory}}/{{lib}}
    ln -sf {{lib_dir}} {{nixos_directory}}/{{lib}}
    ln -sf {{lib_dir}} {{nixos-wsl_directory}}/{{lib}}

lib_unlink:
    @echo -e "{{BOLD + BLUE}}Listing all recipes for dotfiles{{NORMAL}}"
    unlink {{nix-darwin_directory}}/{{lib}}
    unlink {{nixos_directory}}/{{lib}}
    unlink {{nixos-wsl_directory}}/{{lib}}