# https://taskfile.dev

version: '3'

vars:
  USER_NIX_DIR: "$HOME/.config/nix"
  USER_NIX_CONF: "$HOME/.config/nix/nix.conf"
  DOTFILES_NIX_CONF: "{{.TASKFILE_DIR}}/nix.conf"

tasks:
  default:
    desc: Initialize setup for base nix + home-manager setup
    prompt: Do you want to initialize setup for base nix + home-manager setup?
    deps: [up]
    cmds:
      - task: link
  up:
    desc: Update all flake inputs
    cmds:
      - nix flake update
  
  # LINKING AND SETUP THE IMPORTANT FILES
  link:
    desc: Symlink the nix.conf to the official if it exists
    run: when_changed
    preconditions: # requirements
      - sh: test -f {{.DOTFILES_NIX_CONF}}
        msg: '{{.DOTFILES_NIX_CONF}} must exist before linking step'
    status: # status
      - test -d {{.USER_NIX_DIR}}
      - test -L {{.USER_NIX_CONF}}
    cmds:
      - mkdir -p {{.USER_NIX_DIR}}
      - ln -hs {{.DOTFILES_NIX_CONF}} {{.USER_NIX_CONF}}
  unlink:
    desc: Unlink the symlink created to nix.conf if created
    run: when_changed
    preconditions: # requirements
      - sh: test -L {{.USER_NIX_CONF}}
        msg: '{{.USER_NIX_CONF}} is NOT a symlink to remove.'
    cmds:
      - rm {{.USER_NIX_CONF}}
      - rmdir {{.USER_NIX_DIR}}