# https://taskfile.dev

version: '3'

vars:
  MODULES_DIR: '{{.TASKFILE_DIR}}/modules'
  NIXDARWIN_DIR: '/etc/nix-darwin'

tasks:
  default:
    desc: Initialize setup for nix-darwin
    prompt: Do you want to intiialize setup for nix-darwin?
    deps: [up]
    cmds:
      - task: link
  up:
    desc: Update all flake inputs
    cmds:
      - nix flake update

  # LINKING AND SETUP THE IMPORTANT FILES
  link:
    desc: Symlink the nix-darwin config to /etc/nix-darwin
    run: when_changed
    status: # status checks
      - test -L {{.NIXDARWIN_DIR}}
    cmds:
      - sudo ln -hs {{.TASKFILE_DIR}} {{.NIXDARWIN_DIR}}

  clean:
    desc: Cleanup nix-darwin symlink at /etc/nix-darwin
    run: when_changed
    preconditions:
      - sh: test -L {{.NIXDARWIN_DIR}}
        msg: '{{.NIXDARWIN_DIR}} needs to exist and be a symlink before removing'
    cmds:
      - sudo rm {{.NIXDARWIN_DIR}}