# https://taskfile.dev

# sudo: you need the -H flag to use the local user environment for $HOME, otherwise it will default to root home `/var/root` : small bug fix

version: '3'

tasks:
  default:
    desc: Switch / rebuild nix-darwin configuration
    cmds:
      - sudo -H darwin-rebuild switch --flake {{.TASKFILE_DIR}}#{{.NIXCONFIG}}

  init:
    desc: First time init nix-darwin
    cmds:
      - sudo -H nix --extra-experimental-features "nix-command flakes" run nix-darwin/nix-darwin-{{.NIXPKGSVERSION}}#darwin-rebuild -- switch --flake {{.TASKFILE_DIR}}#{{.NIXCONFIG}}

  status:
    desc: Current nix config and version
    cmds:
      - echo -e "\033[1;34mCurrently on nix-darwin '{{.NIXCONFIG}}' configuration at version {{.NIXPKGSVERSION}}\033[0m"
  
  update:
    desc: Update all flake inputs
    cmds:
      - nix flake update

  match-lts-channel:
    desc: Match the nix channels with the nix-darwin lts version. (Unable to install the latest packages on a per-package basis if needed)
    prompt: Warning! This will remove the `nixpkgs` channel and replace it with the nixpkgs-XX-darwin version
    status:
      - sudo -H nix-channel --list | (grep nixpkgs-{{.NIXPKGSVERSION}}-darwin && exit 0)
    cmds:
      - sudo -H nix-channel --remove nixpkgs
      - sudo -H nix-channel --add https://nixos.org/channels/nixpkgs-{{.NIXPKGSVERSION}}-darwin nixpkgs
      - sudo -H nix-channel --update

  unstable-channel:
    desc: Update the nix channels with unstable. (Recommended)
    prompt: Warning! This will remove the `nixpkgs` channel and replace it with the nixpkgs-unstable version
    status:
      - sudo -H nix-channel --list | (grep nixpkgs-unstable && exit 0)
    cmds:
      - sudo -H nix-channel --remove nixpkgs
      - sudo -H nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
      - sudo -H nix-channel --update