# https://taskfile.dev


# sudo: you need the -H flag to use the local user environment for $HOME, otherwise it will default to root home `/var/root` : small bug fix

version: '3'

vars:
  VERSION: "25.05"

tasks:
  default:
    desc: Switch / rebuild nix-darwin configuration
    deps: [up]
    cmds:
      - sudo -H darwin-rebuild switch
  
  init:
    desc: First time init nix-darwin
    deps: [up]
    cmds:
      - sudo -H nix run nix-darwin/nix-darwin-{{.VERSION}}#darwin-rebuild -- switch

  up:
    desc: Update all flake inputs
    cmds:
      - nix flake update