# https://taskfile.dev


# sudo: you need the -H flag to use the local user environment for $HOME, otherwise it will default to root home `/var/root` : small bug fix

version: '3'

vars:
  MODULES_DIR: '{{.TASKFILE_DIR}}/modules'
  NIXDARWIN_DIR: '/etc/nix-darwin'
  VERSION: "25.05"

tasks:
  default:
    desc: Switch / rebuild nix-darwin configuration
    deps: [up, link_add]
    cmds:
      - sudo -H darwin-rebuild switch
  
  init:
    desc: First time init nix-darwin
    deps: [up, link_add]
    cmds:
      - sudo -H nix run nix-darwin/nix-darwin-{{.VERSION}}#darwin-rebuild -- switch

  up:
    desc: Update all flake inputs
    cmds:
      - nix flake update

  # LINKING AND SETUP THE IMPORTANT FILES
  link_add:
    desc: Symlink the nix-darwin config to /etc/nix-darwin
    run: when_changed
    status: # status checks
      - test -L {{.NIXDARWIN_DIR}}
    cmds:
      - sudo ln -hs {{.TASKFILE_DIR}} {{.NIXDARWIN_DIR}}

  link_remove:
    desc: Cleanup nix-darwin symlink at /etc/nix-darwin
    run: when_changed
    preconditions:
      - sh: test -L {{.NIXDARWIN_DIR}}
        msg: '{{.NIXDARWIN_DIR}} needs to exist and be a symlink before removing'
    cmds:
      - sudo rm {{.NIXDARWIN_DIR}}