# https://taskfile.dev

version: '3'

vars:
  VERSION: "25.05"


tasks:
  default:
    desc: Switch / rebuild nixos configuration
    cmds:

  init:
    desc: First time nixos switch/build
    cmds:

  up:
    desc: Update all flake inputs
    cmds:
      - nix flake update